=== swiss-art-research-net/metaphacts-community/project/jsonSchemas/PlatformWebBuild.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Defines schema for `platform-web-build.json` files in metaphactory platform",
  "type": "object",
  "properties": {
    "$schema": true,
    "entries": {
      "type": "object",
      "description": "Exported Webpack entries to build.",
      "additionalProperties": {
        "type": "string"
      }
    },
    "stableEntryNames": {
      "type": "array",
      "description": "Entry names which should not be rewritten by Webpack.",
      "items": {
        "type": "string"
      }
    },
    "aliases": {
      "type": "object",
      "description": "Exported Webpack module aliases.",
      "additionalProperties": {
        "type": "string"
      }
    },
    "extensions": {
      "type": "array",
      "description": "Exported Webpack entries to execute on platform initialization.",
      "items": {
        "type": "string"
      }
    },
    "cssModulesBasedComponents": {
      "type": "array",
      "description": "Directories where SCSS files should be built in CSS-modules aware mode",
      "items": {
        "type": "string"
      }
    },
    "generatedJsonSchemas": {
      "type": "array",
      "description": "TypeScript interface names to generate schemas from in addition to schemas for component props.",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false
}

=== swiss-art-research-net/metaphacts-community/metaphacts-platform/web/platform-web-build.json
{
  "entries": {
    "app": "src/main/app/ts/app.ts",
    "page-renderer": "src/main/app/ts/external/PageRenderer.ts"
  },
  "aliases": {
    "platform/app": "src/main/app/ts",
    "platform/api": "src/main/api",
    "platform/components": "src/main/components",
    "platform/styling": "src/main/styling",
    "basic-styles.scss": "src/main/styling/basic.scss",
    "ontodia": "../ontodia"
  },
  "cssModulesBasedComponents": [
    "src/main/components/admin/config-manager",
    "src/main/components/admin/namespace-manager",
    "src/main/components/admin/create-new-page",
    "src/main/components/admin/repositories",
    "src/main/components/admin/log-browser",
    "src/main/components/admin/repository-switch",
    "src/main/components/admin/page-view-config",
    "src/main/components/3-rd-party/ontodia",
    "src/main/components/dnd",
    "src/main/components/documentation",
    "src/main/components/language-switch",
    "src/main/components/persistence",
    "src/main/components/semantic/data-table",
    "src/main/components/semantic/lazy-tree",
    "src/main/components/semantic/tree",
    "src/main/components/sets/views",
    "src/main/components/ui/highlight",
    "src/main/components/ui/reorderable-list",
    "src/main/components/forms/file-manager",
    "src/main/components/workflow",
    "src/main/components/sparql-editor"
  ],
  "generatedJsonSchemas": [
    "BaseCanvasEventData",
    "BaseOntodiaConfig",
    "BaseOntodiaListenEventData",
    "BuiltInEventData",
    "CanvasConfig",
    "CanvasWidgetConfig",
    "ChartTooltipData",
    "ClassTreeConfig",
    "ElementSearchConfig",
    "EventProxyConfig",
    "EventTargetRefreshConfig",
    "EventTargetTemplateRenderConfig",
    "EventTriggerConfig",
    "FieldDefinitionConfig",
    "FieldDependency",
    "FieldInputOverrideConfig",
    "FileInputConfig",
    "InstancesSearchConfig",
    "KnowledgePanelConfig",
    "KnowledgePanelEventData",
    "KnowledgePanelFrameConfig",
    "KnowledgePanelTriggerConfig",
    "LookupDataQuery",
    "MultipleFieldConstraint",
    "NavigatorWidgetConfig",
    "OntodiaDataProvidersConfig",
    "OntodiaEntityMetadataProps",
    "OntodiaFieldConfigurationConfig",
    "OntodiaListenEventData",
    "OntodiaRdfDataProviderConfig",
    "OntodiaSaveButtonConfig",
    "OntodiaSparqlDataProviderConfig",
    "OntodiaTriggerEventData",
    "InstancesSearchEventData",
    "ResourceEditorFormConfig",
    "RedirectActionProps",
    "SemanticCarouselConfig",
    "SemanticChartConfig",
    "SemanticConfigProps",
    "SemanticFacetConfig",
    "SemanticFormBasedQueryConfig",
    "SemanticGraphBreadthFirstLayoutConfig",
    "SemanticGraphCircleLayoutConfig",
    "SemanticGraphConcentricLayoutConfig",
    "SemanticGraphConfig",
    "SemanticGraphCoseBilkentLayoutConfig",
    "SemanticGraphCoseLayoutConfig",
    "SemanticGraphExpandCollapseExtensionConfig",
    "SemanticGraphNavigatorExtensionConfig",
    "SemanticGraphPanZoomExtensionConfig",
    "SemanticGraphPresetLayoutConfig",
    "SemanticLazyTreeProps",
    "SemanticLazyTreeTemplateData",
    "SemanticMapConfig",
    "SemanticQueryBuilderConfig",
    "SemanticQueryConfig",
    "SemanticSearchConfig",
    "SemanticSearchKeywordConfig",
    "SemanticSearchQueryConstantConfig",
    "SemanticSearchResultHolderConfig",
    "SemanticSimpleSearchConfig",
    "SemanticTableConfig",
    "SemanticDataTableConfig",
    "SemanticTimelineConfig",
    "SemanticTreeConfig",
    "SemanticUpdateConfig",
    "SemanticUpdateEventData",
    "SparqlDataQuery",
    "SplitPaneConfig",
    "ToolbarConfig",
    "WorkflowCreateConfig",
    "WorkspaceContainerConfig",
    "WorkspaceItemConfig",
    "WorkspaceLayoutConfig"
  ]
}
